/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as WorkspaceTasksRouteImport } from './routes/workspace.tasks'
import { Route as WorkspaceSupportRouteImport } from './routes/workspace.support'
import { Route as WorkspaceSigninRouteImport } from './routes/workspace.signin'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace.settings'
import { Route as WorkspaceEarningsRouteImport } from './routes/workspace.earnings'
import { Route as OnboardingWorkspaceSetupRouteImport } from './routes/onboarding.workspace-setup'
import { Route as DevPipelineRouteImport } from './routes/dev.pipeline'
import { Route as CareersAssessmentRouteImport } from './routes/careers.assessment'
import { Route as CareersApplyRouteImport } from './routes/careers.apply'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as ApiCronEmailsRouteImport } from './routes/api/cron.emails'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth.verify'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth.signout'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const WorkspaceTasksRoute = WorkspaceTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSupportRoute = WorkspaceSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSigninRoute = WorkspaceSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEarningsRoute = WorkspaceEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OnboardingWorkspaceSetupRoute =
  OnboardingWorkspaceSetupRouteImport.update({
    id: '/workspace-setup',
    path: '/workspace-setup',
    getParentRoute: () => OnboardingRoute,
  } as any)
const DevPipelineRoute = DevPipelineRouteImport.update({
  id: '/dev/pipeline',
  path: '/dev/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersAssessmentRoute = CareersAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => CareersRoute,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const ApiCronEmailsRoute = ApiCronEmailsRouteImport.update({
  id: '/api/cron/emails',
  path: '/api/cron/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interview': typeof InterviewRoute
  '/offer': typeof OfferRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/dev/pipeline': typeof DevPipelineRoute
  '/onboarding/workspace-setup': typeof OnboardingWorkspaceSetupRoute
  '/workspace/earnings': typeof WorkspaceEarningsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/signin': typeof WorkspaceSigninRoute
  '/workspace/support': typeof WorkspaceSupportRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/careers/': typeof CareersIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/emails': typeof ApiCronEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interview': typeof InterviewRoute
  '/offer': typeof OfferRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/dev/pipeline': typeof DevPipelineRoute
  '/onboarding/workspace-setup': typeof OnboardingWorkspaceSetupRoute
  '/workspace/earnings': typeof WorkspaceEarningsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/signin': typeof WorkspaceSigninRoute
  '/workspace/support': typeof WorkspaceSupportRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/careers': typeof CareersIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/emails': typeof ApiCronEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/assessment': typeof AssessmentRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/interview': typeof InterviewRoute
  '/offer': typeof OfferRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/apply': typeof CareersApplyRoute
  '/careers/assessment': typeof CareersAssessmentRoute
  '/dev/pipeline': typeof DevPipelineRoute
  '/onboarding/workspace-setup': typeof OnboardingWorkspaceSetupRoute
  '/workspace/earnings': typeof WorkspaceEarningsRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/signin': typeof WorkspaceSigninRoute
  '/workspace/support': typeof WorkspaceSupportRoute
  '/workspace/tasks': typeof WorkspaceTasksRoute
  '/careers/': typeof CareersIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/cron/emails': typeof ApiCronEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/assessment'
    | '/careers'
    | '/contact'
    | '/how-it-works'
    | '/interview'
    | '/offer'
    | '/onboarding'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/workspace'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/dev/pipeline'
    | '/onboarding/workspace-setup'
    | '/workspace/earnings'
    | '/workspace/settings'
    | '/workspace/signin'
    | '/workspace/support'
    | '/workspace/tasks'
    | '/careers/'
    | '/workspace/'
    | '/api/auth/signout'
    | '/api/auth/verify'
    | '/api/cron/emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/assessment'
    | '/contact'
    | '/how-it-works'
    | '/interview'
    | '/offer'
    | '/onboarding'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/dev/pipeline'
    | '/onboarding/workspace-setup'
    | '/workspace/earnings'
    | '/workspace/settings'
    | '/workspace/signin'
    | '/workspace/support'
    | '/workspace/tasks'
    | '/careers'
    | '/workspace'
    | '/api/auth/signout'
    | '/api/auth/verify'
    | '/api/cron/emails'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/assessment'
    | '/careers'
    | '/contact'
    | '/how-it-works'
    | '/interview'
    | '/offer'
    | '/onboarding'
    | '/privacy'
    | '/signin'
    | '/terms'
    | '/workspace'
    | '/careers/$slug'
    | '/careers/apply'
    | '/careers/assessment'
    | '/dev/pipeline'
    | '/onboarding/workspace-setup'
    | '/workspace/earnings'
    | '/workspace/settings'
    | '/workspace/signin'
    | '/workspace/support'
    | '/workspace/tasks'
    | '/careers/'
    | '/workspace/'
    | '/api/auth/signout'
    | '/api/auth/verify'
    | '/api/cron/emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AssessmentRoute: typeof AssessmentRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InterviewRoute: typeof InterviewRoute
  OfferRoute: typeof OfferRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  DevPipelineRoute: typeof DevPipelineRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiCronEmailsRoute: typeof ApiCronEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/workspace/tasks': {
      id: '/workspace/tasks'
      path: '/tasks'
      fullPath: '/workspace/tasks'
      preLoaderRoute: typeof WorkspaceTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/support': {
      id: '/workspace/support'
      path: '/support'
      fullPath: '/workspace/support'
      preLoaderRoute: typeof WorkspaceSupportRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/signin': {
      id: '/workspace/signin'
      path: '/signin'
      fullPath: '/workspace/signin'
      preLoaderRoute: typeof WorkspaceSigninRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/earnings': {
      id: '/workspace/earnings'
      path: '/earnings'
      fullPath: '/workspace/earnings'
      preLoaderRoute: typeof WorkspaceEarningsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/workspace-setup': {
      id: '/onboarding/workspace-setup'
      path: '/workspace-setup'
      fullPath: '/onboarding/workspace-setup'
      preLoaderRoute: typeof OnboardingWorkspaceSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/dev/pipeline': {
      id: '/dev/pipeline'
      path: '/dev/pipeline'
      fullPath: '/dev/pipeline'
      preLoaderRoute: typeof DevPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/assessment': {
      id: '/careers/assessment'
      path: '/assessment'
      fullPath: '/careers/assessment'
      preLoaderRoute: typeof CareersAssessmentRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/apply': {
      id: '/careers/apply'
      path: '/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/api/cron/emails': {
      id: '/api/cron/emails'
      path: '/api/cron/emails'
      fullPath: '/api/cron/emails'
      preLoaderRoute: typeof ApiCronEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
  CareersApplyRoute: typeof CareersApplyRoute
  CareersAssessmentRoute: typeof CareersAssessmentRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
  CareersApplyRoute: CareersApplyRoute,
  CareersAssessmentRoute: CareersAssessmentRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface OnboardingRouteChildren {
  OnboardingWorkspaceSetupRoute: typeof OnboardingWorkspaceSetupRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingWorkspaceSetupRoute: OnboardingWorkspaceSetupRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceEarningsRoute: typeof WorkspaceEarningsRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceSigninRoute: typeof WorkspaceSigninRoute
  WorkspaceSupportRoute: typeof WorkspaceSupportRoute
  WorkspaceTasksRoute: typeof WorkspaceTasksRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceEarningsRoute: WorkspaceEarningsRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceSigninRoute: WorkspaceSigninRoute,
  WorkspaceSupportRoute: WorkspaceSupportRoute,
  WorkspaceTasksRoute: WorkspaceTasksRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AssessmentRoute: AssessmentRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  InterviewRoute: InterviewRoute,
  OfferRoute: OfferRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  DevPipelineRoute: DevPipelineRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiCronEmailsRoute: ApiCronEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
